version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: todolist               
      MYSQL_USER: admin                     
      MYSQL_PASSWORD: admin

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://admin:admin@db:3306/todolist
    env_file:
      - .env
    depends_on:
      - db
    # You can add the createsuperuser command here
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py createsuperuser --noinput --username admin --email admin@example.com"

  collectstatic:
    build: .
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/code
    depends_on:
      - web
